// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sijzvbnbxxnamrajwhds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpanp2Ym5ieHhuYW1yYWp3aGRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTUyNjAsImV4cCI6MjA2MzczMTI2MH0.EVVJyf4v_K6mNkDrWm9qXcuy75H-3QM0ztlEalLCZE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);